import path from "node:path";
import {
  calculateMeteringDelta,
  validateMeteringDeltaIntegrity,
  validateMeteringSnapshotIntegrity,
} from "../codeburn-metering-adapter.mjs";
import {
  CODEX_SESSION_ADAPTER_ID,
  calculateCodexSessionMeteringDelta,
  mapCodexSessionUsage,
  validateCodexSessionMeteringDelta,
  validateCodexSessionMeteringSnapshot,
} from "../codex-session-metering-adapter.mjs";
import {
  mappedCodeBurnUsage,
} from "../lifecycle/common.mjs";
import {
  CATALOG_KNOWN_OPTIONS,
  CATALOG_OPTION_METADATA,
} from "../lifecycle/constants.mjs";
import {
  collectCodeBurnBudgetMeterSnapshot,
  collectCodexSessionBudgetMeterSnapshot,
} from "../lifecycle/project.mjs";
import {
  createOperationContext,
} from "../observability/context.mjs";
import {
  fs,
} from "../runtime/host.mjs";
import {
  PLUGIN_ROOT,
} from "../runtime/paths.mjs";
import {
  codeBurnQuery,
  codexSessionQuery,
} from "./common.mjs";
import {
  output,
} from "./output.mjs";

export const PACKAGE_METADATA = JSON.parse(fs.readFileSync(path.join(PLUGIN_ROOT, "package.json"), "utf8"));

export const VERSION = String(PACKAGE_METADATA.version);

export const DEFAULT_TEMPLATE_DIR = path.join(PLUGIN_ROOT, "templates");

export const BUILT_IN_BUDGET_METER_ADAPTERS = Object.freeze({
  codeburn: Object.freeze({
    id: "codeburn",
    label: "CodeBurn",
    supported_sources: Object.freeze([
      "tokens.total",
      "tokens.input",
      "tokens.output",
      "tokens.cache_read",
      "tokens.cache_write",
      "calls",
      "cost",
    ]),
    buildQuery: codeBurnQuery,
    collect: collectCodeBurnBudgetMeterSnapshot,
    calculateDelta: calculateMeteringDelta,
    validateSnapshot: validateMeteringSnapshotIntegrity,
    validateDelta: validateMeteringDeltaIntegrity,
    mapUsage: mappedCodeBurnUsage,
    assurance: "estimated/advisory_observed",
  }),
  [CODEX_SESSION_ADAPTER_ID]: Object.freeze({
    id: CODEX_SESSION_ADAPTER_ID,
    label: "Codex session",
    supported_sources: Object.freeze([
      "tokens.total",
      "tokens.input",
      "tokens.output",
      "tokens.cache_read",
      "tokens.cache_write",
      "calls",
    ]),
    buildQuery: codexSessionQuery,
    collect: collectCodexSessionBudgetMeterSnapshot,
    calculateDelta: calculateCodexSessionMeteringDelta,
    validateSnapshot: validateCodexSessionMeteringSnapshot,
    validateDelta: validateCodexSessionMeteringDelta,
    mapUsage: mapCodexSessionUsage,
    assurance: "local/advisory_observed",
  }),
});

export const NO_FOLLOW_FLAG = fs.constants.O_NOFOLLOW || 0;

export const LEGACY_BOOLEAN_OPTIONS = new Set([
  "allow-incomplete-contract",
  "allow-unapproved-contract-output",
  "allow-unapproved-output-ref",
  "apply",
  "approve-install",
  "confirm-start",
  "confirm-action",
  "force",
  "full",
  "exact",
  "help",
  "json",
  "merge-allowed",
  "no-open",
  "preserve-status",
  "release-claim",
  "recover",
  "replace-story-contract",
  "revise-contract",
  "strict",
  "trust-custom-rtk-command",
  "version",
]);

export const LEGACY_KNOWN_OPTIONS = new Set([
  ...LEGACY_BOOLEAN_OPTIONS,
  "acceptance",
  "action",
  "adapter",
  "active-time-seconds",
  "actor",
  "actor-email",
  "actor-name",
  "actor-type",
  "after-sha",
  "agent",
  "approval-evidence",
  "approval-source",
  "authorization",
  "authorization-receipt",
  "authority-assurance",
  "artifact",
  "assumption",
  "autonomy-ceiling",
  "authorized-by",
  "authorized-by-email",
  "authorized-by-name",
  "authorized-by-source",
  "authorized-by-type",
  "available-capabilities-file",
  "available-capabilities-json",
  "base-artifact",
  "base",
  "baseline",
  "before",
  "before-sha",
  "body",
  "branch",
  "breakdown",
  "budget-file",
  "budget-json",
  "budget-ref",
  "by",
  "capability",
  "capability-binding-file",
  "capability-binding-json",
  "capability-policy-file",
  "capability-policy-json",
  "capability-recommendation",
  "cli-preset",
  "completion-id",
  "confidence",
  "confirmed-source",
  "constraint",
  "context-file",
  "context-summary",
  "contract",
  "contract-id",
  "command-json",
  "cost-amount",
  "currency",
  "decision-id",
  "default-flow",
  "delivery-unit",
  "delivery-profile",
  "document",
  "delivery",
  "definition",
  "definition-file",
  "definition-json",
  "definition-version",
  "edge",
  "event",
  "evidence",
  "execution-note",
  "expires-at",
  "environment",
  "expected-pr-base",
  "expected-pr-body-sha256",
  "expected-pr-state",
  "expected-pr-title",
  "from",
  "from-email",
  "format",
  "git-event",
  "git-provider",
  "handoff-id",
  "host",
  "host-receipt-file",
  "id",
  "input",
  "intent-file",
  "intent-json",
  "identity-map-file",
  "identity-map-json",
  "item",
  "kb-write",
  "kind",
  "integration",
  "level",
  "limit",
  "local-release-provider",
  "locale",
  "levels",
  "metric",
  "media-type",
  "max-uses",
  "metering-accuracy",
  "metering-source",
  "mode",
  "model",
  "model-calls",
  "new-id",
  "nfr",
  "non-goal",
  "next-step",
  "notes",
  "open-item",
  "overlay",
  "overlay-file",
  "overlay-json",
  "overlay-version",
  "out",
  "outcome",
  "output",
  "output-ref",
  "owner-agent",
  "parent",
  "phase",
  "pr-url",
  "pull-request-provider",
  "preset",
  "pricing-ref",
  "plan-hash",
  "port",
  "profile",
  "profile-file",
  "profile-json",
  "project-id",
  "project-name",
  "project",
  "provider",
  "repository",
  "proposal",
  "proposal-hash",
  "qa",
  "query",
  "query-file",
  "query-json",
  "question",
  "rationale",
  "reason",
  "recovery-nonce",
  "reasoning",
  "rationale-summary",
  "receipt-file",
  "receipt-json",
  "recommendation-file",
  "recommendation-json",
  "related",
  "remote",
  "request-id",
  "request-run-id",
  "request-session-id",
  "request-source",
  "request-summary",
  "request-thread-id",
  "requested-by",
  "requested-by-email",
  "requested-by-name",
  "requested-by-source",
  "requested-by-type",
  "requirement",
  "requirement-title",
  "release-manifest",
  "release-target",
  "root",
  "run-id",
  "scope",
  "scope-id",
  "scope-summary",
  "scope-path",
  "scope-title",
  "section",
  "session-id",
  "session-file",
  "since",
  "source",
  "status",
  "smoke-cwd",
  "smoke-test",
  "step",
  "story",
  "steps",
  "subagent",
  "strict-gate-unit",
  "summary",
  "input-summary",
  "output-summary",
  "explanation",
  "explanation-kind",
  "alternative",
  "task-gate",
  "template",
  "template-dir",
  "target-event",
  "target-root",
  "terminal-status",
  "text",
  "thread-id",
  "title",
  "to-agent",
  "tool",
  "tool-calls",
  "head",
  "input-tokens",
  "output-tokens",
  "generator",
  "extension",
  "allow-action",
  "allow-artifact-type",
  "allow-boundary",
  "allow-subject",
  "allow-use",
  "trace-limit",
  "type",
  "until",
  "rollback",
  "write-path",
  "to",
  "to-email",
  "to-name",
  "validation",
  "view",
  "workflow-preset",
  "redaction-policy",
  "guard-input-json",
]);

export const LEGACY_REPEATABLE_OPTIONS = new Set([
  "acceptance",
  "approval-evidence",
  "allow-action",
  "allow-artifact-type",
  "allow-boundary",
  "allow-subject",
  "allow-use",
  "artifact",
  "assumption",
  "alternative",
  "capability-binding-file",
  "capability-binding-json",
  "capability-recommendation",
  "cli-preset",
  "capability",
  "confirmed-source",
  "constraint",
  "context-file",
  "document",
  "edge",
  "evidence",
  "execution-note",
  "input",
  "input-summary",
  "integration",
  "item",
  "kb-write",
  "levels",
  "metric",
  "nfr",
  "non-goal",
  "open-item",
  "output",
  "output-summary",
  "output-ref",
  "qa",
  "question",
  "related",
  "requirement",
  "section",
  "scope-path",
  "source",
  "tool",
  "validation",
  "target-event",
  "write-path",
]);

export const CLI_COMPATIBILITY_BOOLEAN_OPTIONS = new Set(
  [...LEGACY_BOOLEAN_OPTIONS].filter((name) => !CATALOG_KNOWN_OPTIONS.has(name)),
);

export const CLI_COMPATIBILITY_OPTIONS = new Set(
  [...LEGACY_KNOWN_OPTIONS].filter((name) => !CATALOG_KNOWN_OPTIONS.has(name)),
);

export const CLI_COMPATIBILITY_REPEATABLE_OPTIONS = new Set(
  [...LEGACY_REPEATABLE_OPTIONS].filter((name) => !CATALOG_KNOWN_OPTIONS.has(name)),
);

export const BOOLEAN_OPTIONS = new Set([
  ...CATALOG_OPTION_METADATA.boolean,
  ...CLI_COMPATIBILITY_BOOLEAN_OPTIONS,
]);

export const KNOWN_OPTIONS = new Set([
  ...CATALOG_OPTION_METADATA.known,
  ...CLI_COMPATIBILITY_OPTIONS,
]);

export const REPEATABLE_OPTIONS = new Set([
  ...CATALOG_OPTION_METADATA.repeatable,
  ...CLI_COMPATIBILITY_REPEATABLE_OPTIONS,
]);

export const CLI_OPERATION_CONTEXT = createOperationContext({ operation: "cli.run" });
